package com.mbbatch.domain;

import java.util.Date;

/**
 * Tppsm generated by MyEclipse Persistence Tools
 */

public class Tppsm implements java.io.Serializable {

	// Fields

	private Long psmrfnum;
	private String psmname;
	private String psmdevname;
	private String psmisactive;
	private String psmtype;
	private Long exfield1;
	private Long exfield2;
	private String exfield3;
	private String exfield4;
	private Date createdate;
	private Date modidate;
	private String deleted;
	private Long createdby;

	// Constructors

	/** default constructor */
	public Tppsm() {
	}

	/** minimal constructor */
	public Tppsm(String psmname, String psmisactive, String psmtype,
			Date createdate, Date modidate, String deleted, Long createdby) {
		this.psmname = psmname;
		this.psmisactive = psmisactive;
		this.psmtype = psmtype;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
	}

	/** full constructor */
	public Tppsm(String psmname, String psmdevname, String psmisactive,
			String psmtype, Long exfield1, Long exfield2, String exfield3,
			String exfield4, Date createdate, Date modidate, String deleted,
			Long createdby) {
		this.psmname = psmname;
		this.psmdevname = psmdevname;
		this.psmisactive = psmisactive;
		this.psmtype = psmtype;
		this.exfield1 = exfield1;
		this.exfield2 = exfield2;
		this.exfield3 = exfield3;
		this.exfield4 = exfield4;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
	}

	// Property accessors

	public Long getPsmrfnum() {
		return this.psmrfnum;
	}

	public void setPsmrfnum(Long psmrfnum) {
		this.psmrfnum = psmrfnum;
	}


	public String getPsmname() {
		return this.psmname;
	}

	public void setPsmname(String psmname) {
		this.psmname = psmname;
	}

	public String getPsmdevname() {
		return this.psmdevname;
	}

	public void setPsmdevname(String psmdevname) {
		this.psmdevname = psmdevname;
	}

	public String getPsmisactive() {
		return this.psmisactive;
	}

	public void setPsmisactive(String psmisactive) {
		this.psmisactive = psmisactive;
	}

	public String getPsmtype() {
		return this.psmtype;
	}

	public void setPsmtype(String psmtype) {
		this.psmtype = psmtype;
	}

	public Long getExfield1() {
		return this.exfield1;
	}

	public void setExfield1(Long exfield1) {
		this.exfield1 = exfield1;
	}

	public Long getExfield2() {
		return this.exfield2;
	}

	public void setExfield2(Long exfield2) {
		this.exfield2 = exfield2;
	}

	public String getExfield3() {
		return this.exfield3;
	}

	public void setExfield3(String exfield3) {
		this.exfield3 = exfield3;
	}

	public String getExfield4() {
		return this.exfield4;
	}

	public void setExfield4(String exfield4) {
		this.exfield4 = exfield4;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModidate() {
		return this.modidate;
	}

	public void setModidate(Date modidate) {
		this.modidate = modidate;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

}