package com.mbbatch.domain;

import java.util.Date;

/**
 * Tpsbm generated by MyEclipse Persistence Tools
 */

public class Tpsbm implements java.io.Serializable {

	// Fields

	private Long sbmrfnum;
	private Long sbmcndrfnumcontact;
	private Long sbmpmtrfnum;
	private Long sbmubirfnumsender;
	private Long sbmubirfnumrecvr;
	private Long sbmbprrfnum;
	
	private String sbmsubject;
	private String sbmemailid;
	private String sbmmobile;
	private String sbmtele;
	private String sbmfax;
	private String sbmmessage;
	private Date sbmdate;
	private String sbmisactive;
	private String sbmbtos;
	private Date createdate;
	private Date modidate;
	private String deleted;
	private Long createdby;
	private Long exfield1;
	private String exfield2;
	private String sbmsendername;
	private String sbmvisit;
	private Long sbmprjrfnum;
	private String sbmalert;
	
	//Added For new Contact Form
	private String sbmPrefCallTime;
	private String sbmPhoneChk;
	private String sbmEmailChk;
	private Integer sbmLoanLeads;
	private Long sbmcndownerstatus;
	private Long sbmcndsustatus;
	
	private Long sbmMobileisd;
	private Long sbmisd;
	private Long sbmstd;
	private String sbmSenderUserType;

	public String getSbmSenderUserType() {
		return sbmSenderUserType;
	}

	public void setSbmSenderUserType(String sbmSenderUserType) {
		this.sbmSenderUserType = sbmSenderUserType;
	}

	public Long getSbmcndownerstatus() {
		return sbmcndownerstatus;
	}

	public void setSbmcndownerstatus(Long sbmcndownerstatus) {
		this.sbmcndownerstatus = sbmcndownerstatus;
	}

	public Long getSbmcndsustatus() {
		return sbmcndsustatus;
	}

	public void setSbmcndsustatus(Long sbmcndsustatus) {
		this.sbmcndsustatus = sbmcndsustatus;
	}

	/** default constructor */
	public Tpsbm() {
	}

	/** minimal constructor with association */
	/*
	public Tpsbm(Long sbmrfnum, Tpcnd tpcnd, Tpubi tpubiBySbmubirecv,
			String sbmmessage, Date createdate, Date modidate, String deleted,
			Long createdby) {
		this.sbmrfnum = sbmrfnum;
		this.tpcnd = tpcnd;
		this.tpubiBySbmubirecv = tpubiBySbmubirecv;
		this.sbmmessage = sbmmessage;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
	}
	*/
	/* minimal ctor without association */
	public Tpsbm(Long sbmrfnum, Long sbmcndrfnumcontact, Long sbmubirfnumrecvr,
			String sbmmessage, Date createdate, Date modidate, String deleted,
			Long createdby) {
		this.sbmrfnum = sbmrfnum;
		this.sbmcndrfnumcontact = sbmcndrfnumcontact;
		this.sbmubirfnumrecvr = sbmubirfnumrecvr;
		this.sbmmessage = sbmmessage;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
	}

	/** full constructor with association */
	/*
	public Tpsbm(Long sbmrfnum, Tpcnd tpcnd, Tppmt tppmt,
			Tpubi tpubiBySbmubisender, Tpubi tpubiBySbmubirecv, Tpbpr tpbpr,
			String sbmsubject, String sbmemailid, String sbmmobile,
			String sbmtele, String sbmfax, String sbmmessage, Date sbmdate,
			String sbmisactive, String sbmbtos, Date createdate, Date modidate,
			String deleted, Long createdby, Long exfield1, String exfield2,
			String sbmsendername, String sbmvisit, Long sbmprjrfnum) {
		this.sbmrfnum = sbmrfnum;
		this.tpcnd = tpcnd;
		this.tppmt = tppmt;
		this.tpubiBySbmubisender = tpubiBySbmubisender;
		this.tpubiBySbmubirecv = tpubiBySbmubirecv;
		this.tpbpr = tpbpr;
		this.sbmsubject = sbmsubject;
		this.sbmemailid = sbmemailid;
		this.sbmmobile = sbmmobile;
		this.sbmtele = sbmtele;
		this.sbmfax = sbmfax;
		this.sbmmessage = sbmmessage;
		this.sbmdate = sbmdate;
		this.sbmisactive = sbmisactive;
		this.sbmbtos = sbmbtos;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
		this.exfield1 = exfield1;
		this.exfield2 = exfield2;
		this.sbmsendername = sbmsendername;
		this.sbmvisit = sbmvisit;
		this.sbmprjrfnum = sbmprjrfnum;
	}
	*/
	/** full ctor without association */
	public Tpsbm(Long sbmrfnum, Long sbmcndrfnumcontact, Long sbmpmtrfnum,
			Long sbmubirfnumsender, Long sbmubirfnumrecvr, Long sbmbprrfnum,
			String sbmsubject, String sbmemailid, String sbmmobile,
			String sbmtele, String sbmfax, String sbmmessage, Date sbmdate,
			String sbmisactive, String sbmbtos, Date createdate, Date modidate,
			String deleted, Long createdby, Long exfield1, String exfield2,
			String sbmsendername, String sbmvisit, Long sbmprjrfnum, Integer sbmLoanLeads) {
		this.sbmrfnum = sbmrfnum;
		this.sbmcndrfnumcontact = sbmcndrfnumcontact;
		this.sbmpmtrfnum = sbmpmtrfnum;
		this.sbmubirfnumsender = sbmubirfnumsender;
		this.sbmubirfnumrecvr = sbmubirfnumrecvr;
		this.sbmbprrfnum = sbmbprrfnum;
		this.sbmsubject = sbmsubject;
		this.sbmemailid = sbmemailid;
		this.sbmmobile = sbmmobile;
		this.sbmtele = sbmtele;
		this.sbmfax = sbmfax;
		this.sbmmessage = sbmmessage;
		this.sbmdate = sbmdate;
		this.sbmisactive = sbmisactive;
		this.sbmbtos = sbmbtos;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
		this.exfield1 = exfield1;
		this.exfield2 = exfield2;
		this.sbmsendername = sbmsendername;
		this.sbmvisit = sbmvisit;
		this.sbmprjrfnum = sbmprjrfnum;
		this.sbmLoanLeads = sbmLoanLeads;
	}
	
	public Tpsbm(String sbmemailid, String sbmmobile, Date createdate,String  sbmsendername){
		this.sbmemailid=sbmemailid;
		this.sbmmobile=sbmmobile;
		this.createdate=createdate;
		this.sbmsendername=sbmsendername;
		//System.out.println(sbmemailid+","+sbmmobile+","+createdate+","+sbmsendername);
	}
	// Property accessors

	public Long getSbmrfnum() {
		return this.sbmrfnum;
	}

	public void setSbmrfnum(Long sbmrfnum) {
		this.sbmrfnum = sbmrfnum;
	}

	/* with associations */
	/*
	public Tpcnd getTpcnd() {
		return this.tpcnd;
	}

	public void setTpcnd(Tpcnd tpcnd) {
		this.tpcnd = tpcnd;
	}

	public Tppmt getTppmt() {
		return this.tppmt;
	}

	public void setTppmt(Tppmt tppmt) {
		this.tppmt = tppmt;
	}

	public Tpubi getTpubiBySbmubisender() {
		return this.tpubiBySbmubisender;
	}

	public void setTpubiBySbmubisender(Tpubi tpubiBySbmubisender) {
		this.tpubiBySbmubisender = tpubiBySbmubisender;
	}

	public Tpubi getTpubiBySbmubirecv() {
		return this.tpubiBySbmubirecv;
	}

	public void setTpubiBySbmubirecv(Tpubi tpubiBySbmubirecv) {
		this.tpubiBySbmubirecv = tpubiBySbmubirecv;
	}

	public Tpbpr getTpbpr() {
		return this.tpbpr;
	}

	public void setTpbpr(Tpbpr tpbpr) {
		this.tpbpr = tpbpr;
	}
	*/
	public String getSbmsubject() {
		return this.sbmsubject;
	}

	public void setSbmsubject(String sbmsubject) {
		this.sbmsubject = sbmsubject;
	}

	public String getSbmemailid() {
		return this.sbmemailid;
	}

	public void setSbmemailid(String sbmemailid) {
		this.sbmemailid = sbmemailid;
	}

	public String getSbmmobile() {
		return this.sbmmobile;
	}

	public void setSbmmobile(String sbmmobile) {
		this.sbmmobile = sbmmobile;
	}

	public String getSbmtele() {
		return this.sbmtele;
	}

	public void setSbmtele(String sbmtele) {
		this.sbmtele = sbmtele;
	}

	public String getSbmfax() {
		return this.sbmfax;
	}

	public void setSbmfax(String sbmfax) {
		this.sbmfax = sbmfax;
	}

	public String getSbmmessage() {
		return this.sbmmessage;
	}

	public void setSbmmessage(String sbmmessage) {
		this.sbmmessage = sbmmessage;
	}

	public Date getSbmdate() {
		return this.sbmdate;
	}

	public void setSbmdate(Date sbmdate) {
		this.sbmdate = sbmdate;
	}

	public String getSbmisactive() {
		return this.sbmisactive;
	}

	public void setSbmisactive(String sbmisactive) {
		this.sbmisactive = sbmisactive;
	}

	public String getSbmbtos() {
		return this.sbmbtos;
	}

	public void setSbmbtos(String sbmbtos) {
		this.sbmbtos = sbmbtos;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModidate() {
		return this.modidate;
	}

	public void setModidate(Date modidate) {
		this.modidate = modidate;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	public Long getExfield1() {
		return this.exfield1;
	}

	public void setExfield1(Long exfield1) {
		this.exfield1 = exfield1;
	}

	public String getExfield2() {
		return this.exfield2;
	}

	public void setExfield2(String exfield2) {
		this.exfield2 = exfield2;
	}

	public String getSbmsendername() {
		return this.sbmsendername;
	}

	public void setSbmsendername(String sbmsendername) {
		this.sbmsendername = sbmsendername;
	}

	public String getSbmvisit() {
		return this.sbmvisit;
	}

	public void setSbmvisit(String sbmvisit) {
		this.sbmvisit = sbmvisit;
	}

	public Long getSbmprjrfnum() {
		return this.sbmprjrfnum;
	}

	public void setSbmprjrfnum(Long sbmprjrfnum) {
		this.sbmprjrfnum = sbmprjrfnum;
	}

	/* without associations */
	
	public Long getSbmcndrfnumcontact() {
		return sbmcndrfnumcontact;
	}

	public void setSbmcndrfnumcontact(Long sbmcndrfnumcontact) {
		this.sbmcndrfnumcontact = sbmcndrfnumcontact;
	}

	public Long getSbmpmtrfnum() {
		return sbmpmtrfnum;
	}

	public void setSbmpmtrfnum(Long sbmpmtrfnum) {
		this.sbmpmtrfnum = sbmpmtrfnum;
	}

	public Long getSbmubirfnumsender() {
		return sbmubirfnumsender;
	}

	public void setSbmubirfnumsender(Long sbmubirfnumsender) {
		this.sbmubirfnumsender = sbmubirfnumsender;
	}

	public Long getSbmubirfnumrecvr() {
		return sbmubirfnumrecvr;
	}

	public void setSbmubirfnumrecvr(Long sbmubirfnumrecvr) {
		this.sbmubirfnumrecvr = sbmubirfnumrecvr;
	}

	public Long getSbmbprrfnum() {
		return sbmbprrfnum;
	}

	public void setSbmbprrfnum(Long sbmbprrfnum) {
		this.sbmbprrfnum = sbmbprrfnum;
	}

	public String getSbmalert() {
		return sbmalert;
	}

	public void setSbmalert(String sbmalert) {
		this.sbmalert = sbmalert;
	}
	public String toString()
	{
		return getSbmrfnum().toString();
	}

	public String getSbmPrefCallTime() {
		return sbmPrefCallTime;
	}

	public void setSbmPrefCallTime(String sbmPrefCallTime) {
		this.sbmPrefCallTime = sbmPrefCallTime;
	}

	public String getSbmPhoneChk() {
		return sbmPhoneChk;
	}

	public void setSbmPhoneChk(String sbmPhoneChk) {
		this.sbmPhoneChk = sbmPhoneChk;
	}

	public String getSbmEmailChk() {
		return sbmEmailChk;
	}

	public void setSbmEmailChk(String sbmEmailChk) {
		this.sbmEmailChk = sbmEmailChk;
	}

	public Integer getSbmLoanLeads() {
		return sbmLoanLeads;
	}

	public void setSbmLoanLeads(Integer sbmLoanLeads) {
		this.sbmLoanLeads = sbmLoanLeads;
	}

	public Long getSbmisd() {
		return sbmisd;
	}

	public void setSbmisd(Long sbmisd) {
		this.sbmisd = sbmisd;
	}

	public Long getSbmstd() {
		return sbmstd;
	}

	public void setSbmstd(Long sbmstd) {
		this.sbmstd = sbmstd;
	}

	public Long getSbmMobileisd() {
		return sbmMobileisd;
	}

	public void setSbmMobileisd(Long sbmMobileisd) {
		this.sbmMobileisd = sbmMobileisd;
	}
}