package com.mbbatch.domain;

import java.util.Date;

/**
 * Tplrt generated by MyEclipse Persistence Tools
 */

public class Tplrt implements java.io.Serializable {

	// Fields

	private Long lrtrfnum;
	private Long lrtcndrfnum;
	private Long lrtpriceunit;
	private Long lrtlmtrfnum;
	private String lrtisrent;
	private Double lrtminprice;
	private Double lrtmaxprice;
	private Double lrfavgprice;
	private Date createdate;
	private Date modidate;
	private String deleted;
	private Long createdby;
	private Double sd;
	private Integer count;
	private String deduplication;
	private Long city;

	private Double lrtminpriceOld;
	private Double lrtmaxpriceOld;
	private Double lrfavgpriceOld;

	// Constructors

	/** default constructor */
	public Tplrt() {
	}

	/** full constructor */
	public Tplrt(Long lrtrfnum, Long lrtcndrfnum, Long lrtpriceunit,
			Long lrtlmtrfnum, String lrtisrent, Double lrtminprice,
			Double lrtmaxprice, Double lrfavgprice, Date createdate,
			Date modidate, String deleted, Long createdby, Double sd,
			Integer count, String deduplication, Long city) {
		this.lrtrfnum = lrtrfnum;
		this.lrtcndrfnum = lrtcndrfnum;
		this.lrtpriceunit = lrtpriceunit;
		this.lrtlmtrfnum = lrtlmtrfnum;
		this.lrtisrent = lrtisrent;
		this.lrtminprice = lrtminprice;
		this.lrtmaxprice = lrtmaxprice;
		this.lrfavgprice = lrfavgprice;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
		this.sd = sd;
		this.count = count;
		this.deduplication = deduplication;
		this.city = city;
	}

	// Property accessors

	public Long getLrtrfnum() {
		return this.lrtrfnum;
	}

	public void setLrtrfnum(Long lrtrfnum) {
		this.lrtrfnum = lrtrfnum;
	}

	public Long getLrtcndrfnum() {
		return lrtcndrfnum;
	}

	public void setLrtcndrfnum(Long lrtcndrfnum) {
		this.lrtcndrfnum = lrtcndrfnum;
	}

	public Long getLrtpriceunit() {
		return lrtpriceunit;
	}

	public void setLrtpriceunit(Long lrtpriceunit) {
		this.lrtpriceunit = lrtpriceunit;
	}

	public Long getLrtlmtrfnum() {
		return lrtlmtrfnum;
	}

	public void setLrtlmtrfnum(Long lrtlmtrfnum) {
		this.lrtlmtrfnum = lrtlmtrfnum;
	}

	public String getLrtisrent() {
		return this.lrtisrent;
	}

	public void setLrtisrent(String lrtisrent) {
		this.lrtisrent = lrtisrent;
	}

	public Double getLrtminprice() {
		return this.lrtminprice;
	}

	public void setLrtminprice(Double lrtminprice) {
		this.lrtminprice = lrtminprice;
	}

	public Double getLrtmaxprice() {
		return this.lrtmaxprice;
	}

	public void setLrtmaxprice(Double lrtmaxprice) {
		this.lrtmaxprice = lrtmaxprice;
	}

	public Double getLrfavgprice() {
		return this.lrfavgprice;
	}

	public void setLrfavgprice(Double lrfavgprice) {
		this.lrfavgprice = lrfavgprice;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModidate() {
		return this.modidate;
	}

	public void setModidate(Date modidate) {
		this.modidate = modidate;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	public Double getSd() {
		return sd;
	}

	public void setSd(Double sd) {
		this.sd = sd;
	}

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getDeduplication() {
		return deduplication;
	}

	public void setDeduplication(String deduplication) {
		this.deduplication = deduplication;
	}

	public Long getCity() {
		return city;
	}

	public void setCity(Long city) {
		this.city = city;
	}

	public Double getLrtminpriceOld() {
		return lrtminpriceOld;
	}

	public void setLrtminpriceOld(Double lrtminpriceOld) {
		this.lrtminpriceOld = lrtminpriceOld;
	}

	public Double getLrtmaxpriceOld() {
		return lrtmaxpriceOld;
	}

	public void setLrtmaxpriceOld(Double lrtmaxpriceOld) {
		this.lrtmaxpriceOld = lrtmaxpriceOld;
	}

	public Double getLrfavgpriceOld() {
		return lrfavgpriceOld;
	}

	public void setLrfavgpriceOld(Double lrfavgpriceOld) {
		this.lrfavgpriceOld = lrfavgpriceOld;

	}
	public String toString() {
		return this.lrtrfnum + "," + this.lrtcndrfnum + "," + this.lrtpriceunit + "," + this.lrtlmtrfnum + "," + this.lrtisrent 
		+ "," + this.lrtminprice + "," + this.lrtmaxprice +	"," + this.lrfavgprice + "," + this.createdate + "," + this.modidate 
		+ "," + this.deleted + "," + this.createdby + "," + this.lrtminpriceOld + "," + this.lrtmaxpriceOld + "," + this.lrfavgpriceOld;
    }
}