package com.mbbatch.domain;

import java.util.Date;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Tppmt generated by MyEclipse Persistence Tools
 */

public class Tppmt implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pmtrfnum;
	private Long pmtubirfnum;
	private Long pmtassignto;
	private Long pmtcndfurnish;
	private Long pmtcndtow;
	private Long pmtcndplunit;
	private Long pmtcndbedrms;
	private Long pmtcndfln;
	private Long pmtcdmrfnum;
	private Long pmtcndtrantty;
	private Long pmtlmtrfnum;
	private Long pmtcndfacing;
	private Long pmtcndtnof;
	private Long pmtpitrfnum;
	private Long pmtcndaoc;
	private Long pmtmoderresult;
	private Long pmtcndcovunit;
	private Long pmtcndproptype;
	private Long pmtcndbathrms;
	private String pmtadid;
	private String pmtlisttype;
	private Long pmtsaleprice;
	private Long pmtrentprice;
	private String pmtdues;
	private Long pmtcndavailunit;
	private String pmtbriefdisc;
	private String pmtdetaildisc;
	private String pmtkeydisc;
	private String pmttnc;
	private String pmtislisted;
	private String pmtisstd;
	private String pmtisactive;
	private String pmtmoderstatus;
	private String pmtmodercomment;
	private Date pmtstartdate;
	private Date pmtenddate;
	private Date createdate;
	private Date modidate;
	private String deleted;
	private Long createdby;
	private Long exfield1;
	private String exfield2;
	private String pmtcovarea;
	private String pmtplarea;
	private String pmtflrty;
	private String pmtwoodwrk;
	private String pmtwallfin;
	private String pmttvphone;
	private String pmtwatersup;
	private String pmtnearhos;
	private String pmtnearair;
	private String pmtnearrail;
	private String pmtnearsch;
	private String pmtnearbank;
	private String pmtnearmetro;
	private String pmtlmandnei;
	private String pmtcitycen;
	private Long pmtnfviews;
	private String pmtisvirtual;
	private String pmtadcode;
	private Long pmtunquser;
	private Long editedby;
	private Date rankdate;
	private String pmtsource;
	private Integer contactsviewed;
	private Date pmtresponsetime;
	private String pmtsapsalesorg;
	private String pmtsapsalesoffice;
	private Long pmtcndbalconies;
	private Date pmtavaildate;
	private String priceNegotiableFlag;
	private Long pmtubisuperuser;
	private Double pmtcarpetarea;
	private Long pmtcndcarpetunit;
	private String pmtcndamenityfacing;
/*	private Tpmat tpmat;
	private Tppit tppit;*/
	/* add for SortCode revamp*/
	private String pmtPriceCategory;
	private Long pmtCndListtype;
	private Double pmtCompletionScore;
	private Long  pmtuotrfnum;
	private Date locrankdate;

	//Added new code for property modration tracking
	private Long pmtmodertag;
	private Integer pmtmodpriority;

	/**
	 * Test Many to one on TPUBI
	 */
	private Tpubi tpubi;
	/*private Tpcat tpcat;
	
	public Tpcat getTpcat() {
		return tpcat;
	}

	public void setTpcat(Tpcat tpcat) {
		this.tpcat = tpcat;
	}*/

	/**
	 * Default Constructor
	 */
	public Tppmt(){
	}

	/**
	 * Constructor
	 *  added for func tppmtDao.findSimilarPmtForRank
	 * @param createdate  - Date
	 * @param rankdate -  Date
	 */

	public Tppmt(Date createdate,Date rankdate){
		this.createdate = createdate!=null?new Date(createdate.getTime()):null;
		this.rankdate 	= rankdate!=null?new Date(rankdate.getTime()):null;
	}

	/**
	 * Full Constructor
	 */
	public Tppmt(Long pmtrfnum, Long pmtubirfnum, Long pmtassignto, Long pmtcndfurnish,
			Long pmtcndtow, Long pmtcndplunit, Long pmtcndbedrms,
			Long pmtcndfln, Long pmtcdmrfnum, Long pmtcndtrantty,
			Long pmtlmtrfnum, Long pmtcndfacing, Long pmtcndtnof,
			Long pmtpitrfnum, Long pmtcndaoc, Long pmtmoderresult,
			Long pmtcndcovunit, Long pmtcndproptype, Long pmtcndbathrms,
			String pmtadid, String pmtlisttype, Long pmtsaleprice,
			Long pmtrentprice, String pmtdues, Long pmtcndavailunit,
			String pmtbriefdisc, String pmtdetaildisc, String pmtkeydisc,
			String pmttnc, String pmtislisted, String pmtisstd,
			String pmtisactive, String pmtmoderstatus, String pmtmodercomment,
			Date pmtstartdate, Date pmtenddate, Date createdate, Date modidate,
			String deleted, Long createdby, Long exfield1, String exfield2,
			String pmtcovarea, String pmtplarea, String pmtflrty,
			String pmtwoodwrk, String pmtwallfin, String pmttvphone,
			String pmtwatersup, String pmtnearhos, String pmtnearair,
			String pmtnearrail, String pmtnearsch, String pmtlmandnei,
			String pmtcitycen, Long pmtnfviews, String pmtisvirtual,
			String pmtadcode, Long pmtunquser, Long editedby, Date rankdate,Date locrankdate,
			String pmtsource, Integer contactsviewed, Date pmtresponsetime,
			String pmtsapsalesorg, String pmtsapsalesoffice,Long pmtcndbalconies,Date pmtavaildate,
			String priceNegotiableFlag,Long pmtubisuperuser,Double pmtcarpetarea,
			Long pmtcndcarpetunit, String pmtcndamenityfacing,String pmtPriceCategory,
			Long pmtCndListtype,Double pmtCompletionScore,Long  pmtuotrfnum) {
		super();
		this.pmtrfnum = pmtrfnum;
		this.pmtubirfnum = pmtubirfnum;
		this.pmtassignto = pmtassignto;
		this.pmtcndfurnish = pmtcndfurnish;
		this.pmtcndtow = pmtcndtow;
		this.pmtcndplunit = pmtcndplunit;
		this.pmtcndbedrms = pmtcndbedrms;
		this.pmtcndfln = pmtcndfln;
		this.pmtcdmrfnum = pmtcdmrfnum;
		this.pmtcndtrantty = pmtcndtrantty;
		this.pmtlmtrfnum = pmtlmtrfnum;
		this.pmtcndfacing = pmtcndfacing;
		this.pmtcndtnof = pmtcndtnof;
		this.pmtpitrfnum = pmtpitrfnum;
		this.pmtcndaoc = pmtcndaoc;
		this.pmtmoderresult = pmtmoderresult;
		this.pmtcndcovunit = pmtcndcovunit;
		this.pmtcndproptype = pmtcndproptype;
		this.pmtcndbathrms = pmtcndbathrms;
		this.pmtadid = pmtadid;
		this.pmtlisttype = pmtlisttype;
		this.pmtsaleprice = pmtsaleprice;
		this.pmtrentprice = pmtrentprice;
		this.pmtdues = pmtdues;
		this.pmtcndavailunit = pmtcndavailunit;
		this.pmtbriefdisc = pmtbriefdisc;
		this.pmtdetaildisc = pmtdetaildisc;
		this.pmtkeydisc = pmtkeydisc;
		this.pmttnc = pmttnc;
		this.pmtislisted = pmtislisted;
		this.pmtisstd = pmtisstd;
		this.pmtisactive = pmtisactive;
		this.pmtmoderstatus = pmtmoderstatus;
		this.pmtmodercomment = pmtmodercomment;
		this.pmtstartdate = pmtstartdate;
		this.pmtenddate = pmtenddate;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
		this.exfield1 = exfield1;
		this.exfield2 = exfield2;
		this.pmtcovarea = pmtcovarea;
		this.pmtplarea = pmtplarea;
		this.pmtflrty = pmtflrty;
		this.pmtwoodwrk = pmtwoodwrk;
		this.pmtwallfin = pmtwallfin;
		this.pmttvphone = pmttvphone;
		this.pmtwatersup = pmtwatersup;
		this.pmtnearhos = pmtnearhos;
		this.pmtnearair = pmtnearair;
		this.pmtnearrail = pmtnearrail;
		this.pmtnearsch = pmtnearsch;
		this.pmtlmandnei = pmtlmandnei;
		this.pmtcitycen = pmtcitycen;
		this.pmtnfviews = pmtnfviews;
		this.pmtisvirtual = pmtisvirtual;
		this.pmtadcode = pmtadcode;
		this.pmtunquser = pmtunquser;
		this.editedby = editedby;
		this.rankdate = rankdate;
		this.locrankdate = locrankdate;
		this.pmtsource = pmtsource;
		this.contactsviewed = contactsviewed;
		this.pmtresponsetime = pmtresponsetime;
		this.pmtsapsalesorg = pmtsapsalesorg;
		this.pmtsapsalesoffice = pmtsapsalesoffice;
		this.pmtcndbalconies=pmtcndbalconies;
		this.pmtavaildate=pmtavaildate;
		this.priceNegotiableFlag=priceNegotiableFlag;
		this.pmtubisuperuser=pmtubisuperuser;
		this.pmtcarpetarea=pmtcarpetarea;
		this.pmtcndcarpetunit=pmtcndcarpetunit;
		this.pmtcndamenityfacing=pmtcndamenityfacing;
		this.pmtPriceCategory=pmtPriceCategory;
		this.pmtCndListtype=pmtCndListtype;
		this.pmtCompletionScore=pmtCompletionScore;
		this.pmtuotrfnum=pmtuotrfnum;
	}


	public Tppmt(Long pmtrfnum, Long pmtubirfnum, Long pmtassignto, Long pmtcndfurnish,
			Long pmtcndtow, Long pmtcndplunit, Long pmtcndbedrms,
			Long pmtcndfln, Long pmtcdmrfnum, Long pmtcndtrantty,
			Long pmtlmtrfnum, Long pmtcndfacing, Long pmtcndtnof,
			Long pmtpitrfnum, Long pmtcndaoc, Long pmtmoderresult,
			Long pmtcndcovunit, Long pmtcndproptype, Long pmtcndbathrms,
			String pmtadid, String pmtlisttype, Long pmtsaleprice,
			Long pmtrentprice, String pmtdues, Long pmtcndavailunit,
			String pmtbriefdisc, String pmtdetaildisc, String pmtkeydisc,
			String pmttnc, String pmtislisted, String pmtisstd,
			String pmtisactive, String pmtmoderstatus, String pmtmodercomment,
			Date pmtstartdate, Date pmtenddate, Date createdate, Date modidate,
			String deleted, Long createdby, Long exfield1, String exfield2,
			String pmtcovarea, String pmtplarea, String pmtflrty,
			String pmtwoodwrk, String pmtwallfin, String pmttvphone,
			String pmtwatersup, String pmtnearhos, String pmtnearair,
			String pmtnearrail, String pmtnearsch, String pmtlmandnei,
			String pmtcitycen, Long pmtnfviews, String pmtisvirtual,
			String pmtadcode, Long pmtunquser, Long editedby, Date rankdate,Date locrankdate,
			String pmtsource, Integer contactsviewed, Date pmtresponsetime,
			String pmtsapsalesorg, String pmtsapsalesoffice) {
		super();
		this.pmtrfnum = pmtrfnum;
		this.pmtubirfnum = pmtubirfnum;
		this.pmtassignto = pmtassignto;
		this.pmtcndfurnish = pmtcndfurnish;
		this.pmtcndtow = pmtcndtow;
		this.pmtcndplunit = pmtcndplunit;
		this.pmtcndbedrms = pmtcndbedrms;
		this.pmtcndfln = pmtcndfln;
		this.pmtcdmrfnum = pmtcdmrfnum;
		this.pmtcndtrantty = pmtcndtrantty;
		this.pmtlmtrfnum = pmtlmtrfnum;
		this.pmtcndfacing = pmtcndfacing;
		this.pmtcndtnof = pmtcndtnof;
		this.pmtpitrfnum = pmtpitrfnum;
		this.pmtcndaoc = pmtcndaoc;
		this.pmtmoderresult = pmtmoderresult;
		this.pmtcndcovunit = pmtcndcovunit;
		this.pmtcndproptype = pmtcndproptype;
		this.pmtcndbathrms = pmtcndbathrms;
		this.pmtadid = pmtadid;
		this.pmtlisttype = pmtlisttype;
		this.pmtsaleprice = pmtsaleprice;
		this.pmtrentprice = pmtrentprice;
		this.pmtdues = pmtdues;
		this.pmtcndavailunit = pmtcndavailunit;
		this.pmtbriefdisc = pmtbriefdisc;
		this.pmtdetaildisc = pmtdetaildisc;
		this.pmtkeydisc = pmtkeydisc;
		this.pmttnc = pmttnc;
		this.pmtislisted = pmtislisted;
		this.pmtisstd = pmtisstd;
		this.pmtisactive = pmtisactive;
		this.pmtmoderstatus = pmtmoderstatus;
		this.pmtmodercomment = pmtmodercomment;
		this.pmtstartdate = pmtstartdate;
		this.pmtenddate = pmtenddate;
		this.createdate = createdate;
		this.modidate = modidate;
		this.deleted = deleted;
		this.createdby = createdby;
		this.exfield1 = exfield1;
		this.exfield2 = exfield2;
		this.pmtcovarea = pmtcovarea;
		this.pmtplarea = pmtplarea;
		this.pmtflrty = pmtflrty;
		this.pmtwoodwrk = pmtwoodwrk;
		this.pmtwallfin = pmtwallfin;
		this.pmttvphone = pmttvphone;
		this.pmtwatersup = pmtwatersup;
		this.pmtnearhos = pmtnearhos;
		this.pmtnearair = pmtnearair;
		this.pmtnearrail = pmtnearrail;
		this.pmtnearsch = pmtnearsch;
		this.pmtlmandnei = pmtlmandnei;
		this.pmtcitycen = pmtcitycen;
		this.pmtnfviews = pmtnfviews;
		this.pmtisvirtual = pmtisvirtual;
		this.pmtadcode = pmtadcode;
		this.pmtunquser = pmtunquser;
		this.editedby = editedby;
		this.rankdate = rankdate;
		this.locrankdate = locrankdate;
		this.pmtsource = pmtsource;
		this.contactsviewed = contactsviewed;
		this.pmtresponsetime = pmtresponsetime;
		this.pmtsapsalesorg = pmtsapsalesorg;
		this.pmtsapsalesoffice = pmtsapsalesoffice;
	}

	public Long getPmtrfnum() {
		return pmtrfnum;
	}

	public void setPmtrfnum(Long pmtrfnum) {
		this.pmtrfnum = pmtrfnum;
	}

	public Long getPmtubirfnum() {
		return pmtubirfnum;
	}

	public void setPmtubirfnum(Long pmtubirfnum) {
		this.pmtubirfnum = pmtubirfnum;
	}

	public Long getPmtcndfurnish() {
		return pmtcndfurnish;
	}

	public void setPmtcndfurnish(Long pmtcndfurnish) {
		this.pmtcndfurnish = pmtcndfurnish;
	}

	public Long getPmtcndtow() {
		return pmtcndtow;
	}

	public void setPmtcndtow(Long pmtcndtow) {
		this.pmtcndtow = pmtcndtow;
	}

	public Long getPmtcndplunit() {
		return pmtcndplunit;
	}

	public void setPmtcndplunit(Long pmtcndplunit) {
		this.pmtcndplunit = pmtcndplunit;
	}

	public Long getPmtcndbedrms() {
		return pmtcndbedrms;
	}

	public void setPmtcndbedrms(Long pmtcndbedrms) {
		this.pmtcndbedrms = pmtcndbedrms;
	}

	public Long getPmtcndfln() {
		return pmtcndfln;
	}

	public void setPmtcndfln(Long pmtcndfln) {
		this.pmtcndfln = pmtcndfln;
	}

	public Long getPmtcdmrfnum() {
		return pmtcdmrfnum;
	}

	public void setPmtcdmrfnum(Long pmtcdmrfnum) {
		this.pmtcdmrfnum = pmtcdmrfnum;
	}

	public Long getPmtcndtrantty() {
		return pmtcndtrantty;
	}

	public void setPmtcndtrantty(Long pmtcndtrantty) {
		this.pmtcndtrantty = pmtcndtrantty;
	}

	public Long getPmtlmtrfnum() {
		return pmtlmtrfnum;
	}

	public void setPmtlmtrfnum(Long pmtlmtrfnum) {
		this.pmtlmtrfnum = pmtlmtrfnum;
	}

	public Long getPmtcndfacing() {
		return pmtcndfacing;
	}

	public void setPmtcndfacing(Long pmtcndfacing) {
		this.pmtcndfacing = pmtcndfacing;
	}

	public Long getPmtcndtnof() {
		return pmtcndtnof;
	}

	public void setPmtcndtnof(Long pmtcndtnof) {
		this.pmtcndtnof = pmtcndtnof;
	}

	public Long getPmtpitrfnum() {
		return pmtpitrfnum;
	}

	public void setPmtpitrfnum(Long pmtpitrfnum) {
		this.pmtpitrfnum = pmtpitrfnum;
	}

	public Long getPmtcndaoc() {
		return pmtcndaoc;
	}

	public void setPmtcndaoc(Long pmtcndaoc) {
		this.pmtcndaoc = pmtcndaoc;
	}

	public Long getPmtmoderresult() {
		return pmtmoderresult;
	}

	public void setPmtmoderresult(Long pmtmoderresult) {
		this.pmtmoderresult = pmtmoderresult;
	}

	public Long getPmtcndcovunit() {
		return pmtcndcovunit;
	}

	public void setPmtcndcovunit(Long pmtcndcovunit) {
		this.pmtcndcovunit = pmtcndcovunit;
	}

	public Long getPmtcndproptype() {
		return pmtcndproptype;
	}

	public void setPmtcndproptype(Long pmtcndproptype) {
		this.pmtcndproptype = pmtcndproptype;
	}

	public Long getPmtcndbathrms() {
		return pmtcndbathrms;
	}

	public void setPmtcndbathrms(Long pmtcndbathrms) {
		this.pmtcndbathrms = pmtcndbathrms;
	}

	public String getPmtadid() {
		return pmtadid;
	}

	public void setPmtadid(String pmtadid) {
		this.pmtadid = pmtadid;
	}

	public String getPmtlisttype() {
		return pmtlisttype;
	}

	public void setPmtlisttype(String pmtlisttype) {
		this.pmtlisttype = pmtlisttype;
	}

	public Long getPmtsaleprice() {
		return pmtsaleprice;
	}

	public void setPmtsaleprice(Long pmtsaleprice) {
		this.pmtsaleprice = pmtsaleprice;
	}

	public Long getPmtrentprice() {
		return pmtrentprice;
	}

	public void setPmtrentprice(Long pmtrentprice) {
		this.pmtrentprice = pmtrentprice;
	}

	public String getPmtdues() {
		return pmtdues;
	}

	public void setPmtdues(String pmtdues) {
		this.pmtdues = pmtdues;
	}

	public Long getPmtcndavailunit() {
		return pmtcndavailunit;
	}

	public void setPmtcndavailunit(Long pmtcndavailunit) {
		this.pmtcndavailunit = pmtcndavailunit;
	}

	public String getPmtbriefdisc() {
		return pmtbriefdisc;
	}

	public void setPmtbriefdisc(String pmtbriefdisc) {
		this.pmtbriefdisc = pmtbriefdisc;
	}

	public String getPmtdetaildisc() {
		return this.pmtdetaildisc;
	}

	public void setPmtdetaildisc(String pmtdetaildisc) {
		this.pmtdetaildisc = pmtdetaildisc;
	}

	public String getPmtkeydisc() {
		return pmtkeydisc;
	}

	public void setPmtkeydisc(String pmtkeydisc) {
		this.pmtkeydisc = pmtkeydisc;
	}

	public String getPmttnc() {
		return pmttnc;
	}

	public void setPmttnc(String pmttnc) {
		this.pmttnc = pmttnc;
	}

	public String getPmtislisted() {
		return pmtislisted;
	}

	public void setPmtislisted(String pmtislisted) {
		this.pmtislisted = pmtislisted;
	}

	public String getPmtisstd() {
		return pmtisstd;
	}

	public void setPmtisstd(String pmtisstd) {
		this.pmtisstd = pmtisstd;
	}

	public String getPmtisactive() {
		return pmtisactive;
	}

	public void setPmtisactive(String pmtisactive) {
		this.pmtisactive = pmtisactive;
	}

	public String getPmtmoderstatus() {
		return pmtmoderstatus;
	}

	public void setPmtmoderstatus(String pmtmoderstatus) {
		this.pmtmoderstatus = pmtmoderstatus;
	}

	public String getPmtmodercomment() {
		return pmtmodercomment;
	}

	public void setPmtmodercomment(String pmtmodercomment) {
		this.pmtmodercomment = pmtmodercomment;
	}

	public Date getPmtstartdate() {
		return pmtstartdate;
	}

	public void setPmtstartdate(Date pmtstartdate) {
		this.pmtstartdate = pmtstartdate;
	}

	public Date getPmtenddate() {
		return pmtenddate;
	}

	public void setPmtenddate(Date pmtenddate) {
		this.pmtenddate = pmtenddate;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModidate() {
		return modidate;
	}

	public void setModidate(Date modidate) {
		this.modidate = modidate;
	}

	public String getDeleted() {
		return deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public Long getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	public Long getExfield1() {
		return exfield1;
	}

	public void setExfield1(Long exfield1) {
		this.exfield1 = exfield1;
	}

	public String getExfield2() {
		return exfield2;
	}

	public void setExfield2(String exfield2) {
		this.exfield2 = exfield2;
	}

	public String getPmtcovarea() {
		return pmtcovarea;
	}

	public void setPmtcovarea(String pmtcovarea) {
		this.pmtcovarea = pmtcovarea;
	}

	public String getPmtplarea() {
		return pmtplarea;
	}

	public void setPmtplarea(String pmtplarea) {
		this.pmtplarea = pmtplarea;
	}

	public String getPmtflrty() {
		return pmtflrty;
	}

	public void setPmtflrty(String pmtflrty) {
		this.pmtflrty = pmtflrty;
	}

	public String getPmtwoodwrk() {
		return pmtwoodwrk;
	}

	public void setPmtwoodwrk(String pmtwoodwrk) {
		this.pmtwoodwrk = pmtwoodwrk;
	}

	public String getPmtwallfin() {
		return pmtwallfin;
	}

	public void setPmtwallfin(String pmtwallfin) {
		this.pmtwallfin = pmtwallfin;
	}

	public String getPmttvphone() {
		return pmttvphone;
	}

	public void setPmttvphone(String pmttvphone) {
		this.pmttvphone = pmttvphone;
	}

	public String getPmtwatersup() {
		return pmtwatersup;
	}

	public void setPmtwatersup(String pmtwatersup) {
		this.pmtwatersup = pmtwatersup;
	}

	public String getPmtnearhos() {
		return pmtnearhos;
	}

	public void setPmtnearhos(String pmtnearhos) {
		this.pmtnearhos = pmtnearhos;
	}

	public String getPmtnearair() {
		return pmtnearair;
	}

	public void setPmtnearair(String pmtnearair) {
		this.pmtnearair = pmtnearair;
	}

	public String getPmtnearrail() {
		return pmtnearrail;
	}

	public void setPmtnearrail(String pmtnearrail) {
		this.pmtnearrail = pmtnearrail;
	}

	public String getPmtnearsch() {
		return pmtnearsch;
	}

	public void setPmtnearsch(String pmtnearsch) {
		this.pmtnearsch = pmtnearsch;
	}

	public String getPmtlmandnei() {
		return pmtlmandnei;
	}

	public void setPmtlmandnei(String pmtlmandnei) {
		this.pmtlmandnei = pmtlmandnei;
	}

	public String getPmtcitycen() {
		return pmtcitycen;
	}

	public void setPmtcitycen(String pmtcitycen) {
		this.pmtcitycen = pmtcitycen;
	}

	public Long getPmtnfviews() {
		return pmtnfviews;
	}

	public void setPmtnfviews(Long pmtnfviews) {
		this.pmtnfviews = pmtnfviews;
	}

	public String getPmtisvirtual() {
		return pmtisvirtual;
	}

	public void setPmtisvirtual(String pmtisvirtual) {
		this.pmtisvirtual = pmtisvirtual;
	}

	public String getPmtadcode() {
		return pmtadcode;
	}

	public void setPmtadcode(String pmtadcode) {
		this.pmtadcode = pmtadcode;
	}

	public Long getPmtunquser() {
		return pmtunquser;
	}

	public void setPmtunquser(Long pmtunquser) {
		this.pmtunquser = pmtunquser;
	}

	public Long getEditedby() {
		return editedby;
	}

	public void setEditedby(Long editedby) {
		this.editedby = editedby;
	}

	public Date getRankdate() {
		return rankdate;
	}

	public void setRankdate(Date rankdate) {
		this.rankdate = rankdate;
	}

	public String getPmtsource() {
		return pmtsource;
	}

	public void setPmtsource(String pmtsource) {
		this.pmtsource = pmtsource;
	}

	public Integer getContactsviewed() {
		return contactsviewed;
	}

	public void setContactsviewed(Integer contactsviewed) {
		this.contactsviewed = contactsviewed;
	}

	public Date getPmtresponsetime() {
		return pmtresponsetime;
	}

	public void setPmtresponsetime(Date pmtresponsetime) {
		this.pmtresponsetime = pmtresponsetime;
	}

	public String getPmtsapsalesorg() {
		return pmtsapsalesorg;
	}

	public void setPmtsapsalesorg(String pmtsapsalesorg) {
		this.pmtsapsalesorg = pmtsapsalesorg;
	}

	public String getPmtsapsalesoffice() {
		return pmtsapsalesoffice;
	}

	public void setPmtsapsalesoffice(String pmtsapsalesoffice) {
		this.pmtsapsalesoffice = pmtsapsalesoffice;
	}

	public Long getPmtassignto() {
		return pmtassignto;
	}

	public void setPmtassignto(Long pmtassignto) {
		this.pmtassignto = pmtassignto;
	}

	public Long getPmtcndbalconies() {
		return pmtcndbalconies;
	}

	public void setPmtcndbalconies(Long pmtcndbalconies) {
		this.pmtcndbalconies = pmtcndbalconies;
	}

	public Date getPmtavaildate() {
		return pmtavaildate;
	}

	public void setPmtavaildate(Date pmtavaildate) {
		this.pmtavaildate = pmtavaildate;
	}

	public String getPriceNegotiableFlag() {
		return priceNegotiableFlag;
	}

	public void setPriceNegotiableFlag(String priceNegotiableFlag) {
		this.priceNegotiableFlag = priceNegotiableFlag;
	}

	public Long getPmtubisuperuser() {
		return pmtubisuperuser;
	}

	public void setPmtubisuperuser(Long pmtubisuperuser) {
		this.pmtubisuperuser = pmtubisuperuser;
	}

	/*public Tpmat getTpmat() {
		return tpmat;
	}

	public void setTpmat(Tpmat tpmat) {
		this.tpmat = tpmat;
	}

	public Tppit getTppit() {
		return tppit;
	}

	public void setTppit(Tppit tppit) {
		this.tppit = tppit;
	}*/

	public Tpubi getTpubi() {
		return tpubi;
	}

	public void setTpubi(Tpubi tpubi) {
		this.tpubi = tpubi;
	}

	public String getPmtPriceCategory() {
		return pmtPriceCategory;
	}

	public void setPmtPriceCategory(String pmtPriceCategory) {
		this.pmtPriceCategory = pmtPriceCategory;
	}

	public Long getPmtCndListtype() {
		return pmtCndListtype;
	}

	public void setPmtCndListtype(Long pmtCndListtype) {
		this.pmtCndListtype = pmtCndListtype;
	}

	/**
	 * @return the pmtcarpetarea
	 */
	public Double getPmtcarpetarea() {
		return pmtcarpetarea;
	}

	/**
	 * @param pmtcarpetarea the pmtcarpetarea to set
	 */
	public void setPmtcarpetarea(Double pmtcarpetarea) {
		this.pmtcarpetarea = pmtcarpetarea;
	}

	/**
	 * @return the pmtcndcarpetunit
	 */
	public Long getPmtcndcarpetunit() {
		return pmtcndcarpetunit;
	}

	/**
	 * @param pmtcndcarpetunit the pmtcndcarpetunit to set
	 */
	public void setPmtcndcarpetunit(Long pmtcndcarpetunit) {
		this.pmtcndcarpetunit = pmtcndcarpetunit;
	}

	/**
	 * @return the pmtcndamenityfacing
	 */
	public String getPmtcndamenityfacing() {
		return pmtcndamenityfacing;
	}

	/**
	 * @param pmtcndamenityfacing the pmtcndamenityfacing to set
	 */
	public void setPmtcndamenityfacing(String pmtcndamenityfacing) {
		this.pmtcndamenityfacing = pmtcndamenityfacing;
	}

	/**
	 * @return the pmtnearbank
	 */
	public String getPmtnearbank() {
		return pmtnearbank;
	}

	/**
	 * @param pmtnearbank the pmtnearbank to set
	 */
	public void setPmtnearbank(String pmtnearbank) {
		this.pmtnearbank = pmtnearbank;
	}

	/**
	 * @return the pmtnearmetro
	 */
	public String getPmtnearmetro() {
		return pmtnearmetro;
	}

	/**
	 * @param pmtnearmetro the pmtnearmetro to set
	 */
	public void setPmtnearmetro(String pmtnearmetro) {
		this.pmtnearmetro = pmtnearmetro;
	}

	public Double getPmtCompletionScore() {
		return pmtCompletionScore;
	}

	public void setPmtCompletionScore(Double pmtCompletionScore) {
		this.pmtCompletionScore = pmtCompletionScore;
	}

	public Long getPmtuotrfnum() {
		return pmtuotrfnum;
	}

	public void setPmtuotrfnum(Long pmtuotrfnum) {
		this.pmtuotrfnum = pmtuotrfnum;
	}

	public Date getLocrankdate() {
		return locrankdate;
	}

	public void setLocrankdate(Date locrankdate) {
		this.locrankdate = locrankdate;
	}
	public Long getPmtmodertag() {
		return pmtmodertag;
	}

	public void setPmtmodertag(Long pmtmodertag) {
		this.pmtmodertag = pmtmodertag;
	}

	public Integer getPmtmodpriority() {
		return pmtmodpriority;
	}

	public void setPmtmodpriority(Integer pmtmodpriority) {
		this.pmtmodpriority = pmtmodpriority;
	}
	
	
	public String toString() {
        return this.pmtrfnum + "," + this.pmtubirfnum + "," + this.pmtcdmrfnum + "," + this.pmtlmtrfnum + "," + this.pmtcndproptype + ","+ this.pmtlisttype + "," +this.pmtsaleprice
		 + "," + this.pmtrentprice + "," + this.pmtbriefdisc + "," + this.pmtislisted + "," + this.pmtisactive + "," + this.pmtmoderstatus + "," + this.pmtstartdate
		 + "," + this.pmtenddate + "," + this.createdate + "," + this.modidate + "," + this.deleted + "," + this.rankdate + "," + this.locrankdate + "," + this.pmtCndListtype;
    }
    
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((pmtrfnum == null) ? 0 : pmtrfnum.hashCode());
		return result;
	}

	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
		if (obj == null){
			return false;
		}
		if (!(obj instanceof Tppmt)){
			return false;
		}
		Tppmt other = (Tppmt) obj;
		if (pmtrfnum == null) {
			if (other.getPmtrfnum() != null){
				return false;
			}
		} else if (!pmtrfnum.equals(other.getPmtrfnum())){
			return false;
		}
		return true;
	}
}