package com.mbbatch.domain;

import java.util.Date;

/**
 * Tprec generated by MyEclipse Persistence Tools
 */

public class Tpsrec implements java.io.Serializable {

	// Fields

	private Long srrfnum;
	private Long srstype;
	private Long srcndcity;
	private Long srcndstate;
	private Long srcndbudgetmin;
	private Long srcndbudgetmax;
	private Long srcndfloorfrm;
	private Long srcndfloorto;
	private Long srcovaresfrm;
	private Long srcovareato;
	private Long srcndcovunit;
	private Long srplareafrm;
	private Long srplareato;
	private Long srcndplunit;
	private Long srcndaoc;
	private Long srcndlistingposted;
	private Long srubirfnum;
	private Long srhitcnt;
	private Long srresultcount;
	private Long exfield1;
	private Long exfield2;
	private Long exfield3;
	private Long exfield4;
	private String exfield5;//City
	private String exfield6;//State
	private String exfield7;//Country
	private String exfield8;
	
	
	//private Tplmt tplmt;
	
	private String srsource;
	private String srcatg;
	private String srlocality;
	private String srcndtranstype;
	private String srcndproptype;
	private String srcndbedrms;
	private String srimageoption;
	private String srpostedby;
	private String srdesc;
	private String srcmpcode;
	private Date createdate;
	private String srresultids;
	private String sragentsrchtyp;
	private String sripaddress;
	private Long srsuburb;
	
	
	// Constructors


	public String getSripaddress() {
		return sripaddress;
	}

	public void setSripaddress(String sripaddress) {
		this.sripaddress = sripaddress;
	}

	/** default constructor */
	public Tpsrec (){}

	public Long getSrrfnum() {
		return srrfnum;
	}

	public void setSrrfnum(Long srrfnum) {
		this.srrfnum = srrfnum;
	}

	public Long getSrstype() {
		return srstype;
	}

	public void setSrstype(Long srstype) {
		this.srstype = srstype;
	}

	public Long getSrcndcity() {
		return srcndcity;
	}

	public void setSrcndcity(Long srcndcity) {
		this.srcndcity = srcndcity;
	}

	

	public Long getSrcndstate() {
		return srcndstate;
	}

	public void setSrcndstate(Long srcndstate) {
		this.srcndstate = srcndstate;
	}

	public Long getSrcndbudgetmin() {
		return srcndbudgetmin;
	}

	public void setSrcndbudgetmin(Long srcndbudgetmin) {
		this.srcndbudgetmin = srcndbudgetmin;
	}



	public Long getSrcndbudgetmax() {
		return srcndbudgetmax;
	}

	public void setSrcndbudgetmax(Long srcndbudgetmax) {
		this.srcndbudgetmax = srcndbudgetmax;
	}

	public Long getSrcndfloorfrm() {
		return srcndfloorfrm;
	}

	public void setSrcndfloorfrm(Long srcndfloorfrm) {
		this.srcndfloorfrm = srcndfloorfrm;
	}

	public Long getSrcndfloorto() {
		return srcndfloorto;
	}

	public void setSrcndfloorto(Long srcndfloorto) {
		this.srcndfloorto = srcndfloorto;
	}

	public Long getSrcovaresfrm() {
		return srcovaresfrm;
	}

	public void setSrcovaresfrm(Long srcovaresfrm) {
		this.srcovaresfrm = srcovaresfrm;
	}

	public Long getSrcovareato() {
		return srcovareato;
	}

	public void setSrcovareato(Long srcovareato) {
		this.srcovareato = srcovareato;
	}

	public Long getSrcndcovunit() {
		return srcndcovunit;
	}

	public void setSrcndcovunit(Long srcndcovunit) {
		this.srcndcovunit = srcndcovunit;
	}

	public Long getSrplareafrm() {
		return srplareafrm;
	}

	public void setSrplareafrm(Long srplareafrm) {
		this.srplareafrm = srplareafrm;
	}

	public Long getSrplareato() {
		return srplareato;
	}

	public void setSrplareato(Long srplareato) {
		this.srplareato = srplareato;
	}

	public Long getSrcndplunit() {
		return srcndplunit;
	}

	public void setSrcndplunit(Long srcndplunit) {
		this.srcndplunit = srcndplunit;
	}

	public Long getSrcndaoc() {
		return srcndaoc;
	}

	public void setSrcndaoc(Long srcndaoc) {
		this.srcndaoc = srcndaoc;
	}

	public Long getSrcndlistingposted() {
		return srcndlistingposted;
	}

	public void setSrcndlistingposted(Long srcndlistingposted) {
		this.srcndlistingposted = srcndlistingposted;
	}

	public Long getSrubirfnum() {
		return srubirfnum;
	}

	public void setSrubirfnum(Long srubirfnum) {
		this.srubirfnum = srubirfnum;
	}

	public Long getSrhitcnt() {
		return srhitcnt;
	}

	public void setSrhitcnt(Long srhitcnt) {
		this.srhitcnt = srhitcnt;
	}



	public Long getSrresultcount() {
		return srresultcount;
	}

	public void setSrresultcount(Long srresultcount) {
		this.srresultcount = srresultcount;
	}

	public String getSrsource() {
		return srsource;
	}

	public void setSrsource(String srsource) {
		this.srsource = srsource;
	}

	public String getSrcatg() {
		return srcatg;
	}

	public void setSrcatg(String srcatg) {
		this.srcatg = srcatg;
	}

	public String getSrlocality() {
		return srlocality;
	}

	public void setSrlocality(String srlocality) {
		this.srlocality = srlocality;
	}



	public String getSrcndtranstype() {
		return srcndtranstype;
	}

	public void setSrcndtranstype(String srcndtranstype) {
		this.srcndtranstype = srcndtranstype;
	}

	public String getSrcndproptype() {
		return srcndproptype;
	}

	public void setSrcndproptype(String srcndproptype) {
		this.srcndproptype = srcndproptype;
	}

	public String getSrcndbedrms() {
		return srcndbedrms;
	}

	public void setSrcndbedrms(String srcndbedrms) {
		this.srcndbedrms = srcndbedrms;
	}

	public String getSrimageoption() {
		return srimageoption;
	}

	public void setSrimageoption(String srimageoption) {
		this.srimageoption = srimageoption;
	}

	public String getSrpostedby() {
		return srpostedby;
	}

	public void setSrpostedby(String srpostedby) {
		this.srpostedby = srpostedby;
	}

	public String getSrdesc() {
		return srdesc;
	}

	public void setSrdesc(String srdesc) {
		this.srdesc = srdesc;
	}



	public String getSrcmpcode() {
		return srcmpcode;
	}

	public void setSrcmpcode(String srcmpcode) {
		this.srcmpcode = srcmpcode;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Long getExfield1() {
		return exfield1;
	}

	public void setExfield1(Long exfield1) {
		this.exfield1 = exfield1;
	}

	public Long getExfield2() {
		return exfield2;
	}

	public void setExfield2(Long exfield2) {
		this.exfield2 = exfield2;
	}

	public Long getExfield3() {
		return exfield3;
	}

	public void setExfield3(Long exfield3) {
		this.exfield3 = exfield3;
	}

	public Long getExfield4() {
		return exfield4;
	}

	public void setExfield4(Long exfield4) {
		this.exfield4 = exfield4;
	}

	public String getExfield5() {
		return exfield5;
	}

	public void setExfield5(String exfield5) {
		this.exfield5 = exfield5;
	}

	public String getExfield6() {
		return exfield6;
	}

	public void setExfield6(String exfield6) {
		this.exfield6 = exfield6;
	}

	public String getExfield7() {
		return exfield7;
	}

	public void setExfield7(String exfield7) {
		this.exfield7 = exfield7;
	}

	public String getExfield8() {
		return exfield8;
	}

	public void setExfield8(String exfield8) {
		this.exfield8 = exfield8;
	}

	public String getSrresultids() {
		return srresultids;
	}

	public void setSrresultids(String srresultids) {
		this.srresultids = srresultids;
	}

	public String getSragentsrchtyp() {
		return sragentsrchtyp;
	}

	public void setSragentsrchtyp(String sragentsrchtyp) {
		this.sragentsrchtyp = sragentsrchtyp;
	}

	public Long getSrsuburb() {
		return srsuburb;
	}

	public void setSrsuburb(Long srsuburb) {
		this.srsuburb = srsuburb;
	}
	public String toString() {
		return this.srcndcity + ";" + this.srcatg + ";" + this.srsource + ";" + this.srlocality + ";" + this.srcndproptype 
		+ ";" + this.srcndbedrms + ";" + this.createdate +	";" + this.srresultcount;
    }
}