package com.mbbatch.domain;

import java.util.Date;

/**
 * Tpubi generated by MyEclipse Persistence Tools
 */

public class Tpubi implements java.io.Serializable {

	// Fields

	private Long ubirfnum;
	private Long ubicndmaristat;
	private Long ubiassignto;
	private Long ubicndoccupation;
	private Long ubicndstate;
	private Long ubicndcountry;
	private Long ubicndeducation;
	private Long ubisuperuser;
	private Long ubicndcity;
	private Long ubicndtitle;
	private Long ubicndhouseincm;
	private String ubilogin;
	private String ubipass;
	private String ubihintq;
	private String ubihintans;
	private String ubifname;
	private String ubimname;
	private String ubilname;
	private String ubiaddr1;
	private String ubiaddr2;
	private String ubiothercity;
	private String ubiotherstate;
	private Long ubicndzip;
	private String ubiaddrvisible;
	private String ubiphone;
	private String ubiphone2;
	private String ubiphonevisible;
	private String ubimobile;
	private String ubifax;
	private String ubiemail;
	private String ubiemail2;
	private String ubiemailvisible;
	private String ubicndcontmode;
	private String ubiurl;
	private String ubigender;
	private Date ubidob;
	private String ubiintrests;
	private Date ubilastaccess;
	private Date createdate;
	private Date modidate;
	private String ubiactive;
	private String ubiisverified;
	private String deleted;
	private Long createdby;
	private Long exfiled1;
	private String exfield2;
	private String ubiusertype;
	private String ubipeavail;
	private String ubihavecall;
	private String ubicallmsg;
	private String ubiispaid;
	private String ubiadcode;
	private Long ubiunquser;
	private String ubiblockuser;
	private String mailblock;
	private String exfield3;
	private String exfield4;
	private Long usermodassignto;
	private String isregistered;
	private String ubidispupfront="N";
	
	private String ubiemailverified;
	private Long ubiprimarymobile;
	private String ubiemailalternate;
	private String ubimailoption;
	private String ubiautoregister;
	private Integer ubifreelisting;
	private String ubitoken ;
	private Long ubiprimarymobileisd;
	private Long ubiphonestd;
	private Long ubicndphoneisd;
	private int ubiSpamscore; 

	private Integer ubiqualityscore;
	// Full Constructors
	
	public Integer getUbiqualityscore() {
		return ubiqualityscore;
	}

	public void setUbiqualityscore(Integer ubiqualityscore) {
		this.ubiqualityscore = ubiqualityscore;
	}

	public String getUbimailoption() {
		return ubimailoption;
	}

	public void setUbimailoption(String ubimailoption) {
		this.ubimailoption = ubimailoption;
	}	

	public Tpubi(Long ubirfnum, Long ubicndmaristat, Long ubiassignto,
			Long ubicndoccupation, Long ubicndstate, Long ubicndcountry,
			Long ubicndeducation, Long ubisuperuser, Long ubicndcity,
			Long ubicndtitle, Long ubicndhouseincm, String ubilogin,
			String ubipass, String ubihintq, String ubihintans,
			String ubifname, String ubimname, String ubilname, String ubiaddr1,
			String ubiaddr2, String ubiothercity, String ubiotherstate,
			Long ubicndzip, String ubiaddrvisible, String ubiphone,
			String ubiphone2, String ubiphonevisible, String ubimobile,
			String ubifax, String ubiemail, String ubiemail2,
			String ubiemailvisible, String ubicndcontmode, String ubiurl,
			String ubigender, Date ubidob, String ubiintrests,
			Date ubilastaccess, Date createdate, Date modidate,
			String ubiactive, String ubiisverified, String deleted,
			Long createdby, Long exfiled1, String exfield2, String ubiusertype,
			String ubipeavail, String ubihavecall, String ubicallmsg,
			String ubiispaid, String ubiadcode, Long ubiunquser,
			String ubiblockuser, String mailblock, String exfield3,
			String exfield4, Long usermodassignto, String isregistered) {
		super();
		this.ubirfnum = ubirfnum;
		this.ubicndmaristat = ubicndmaristat;
		this.ubiassignto = ubiassignto;
		this.ubicndoccupation = ubicndoccupation;
		this.ubicndstate = ubicndstate;
		this.ubicndcountry = ubicndcountry;
		this.ubicndeducation = ubicndeducation;
		this.ubisuperuser = ubisuperuser;
		this.ubicndcity = ubicndcity;
		this.ubicndtitle = ubicndtitle;
		this.ubicndhouseincm = ubicndhouseincm;
		this.ubilogin = ubilogin;
		this.ubipass = ubipass;
		this.ubihintq = ubihintq;
		this.ubihintans = ubihintans;
		this.ubifname = ubifname;
		this.ubimname = ubimname;
		this.ubilname = ubilname;
		this.ubiaddr1 = ubiaddr1;
		this.ubiaddr2 = ubiaddr2;
		this.ubiothercity = ubiothercity;
		this.ubiotherstate = ubiotherstate;
		this.ubicndzip = ubicndzip;
		this.ubiaddrvisible = ubiaddrvisible;
		this.ubiphone = ubiphone;
		this.ubiphone2 = ubiphone2;
		this.ubiphonevisible = ubiphonevisible;
		this.ubimobile = ubimobile;
		this.ubifax = ubifax;
		this.ubiemail = ubiemail;
		this.ubiemail2 = ubiemail2;
		this.ubiemailvisible = ubiemailvisible;
		this.ubicndcontmode = ubicndcontmode;
		this.ubiurl = ubiurl;
		this.ubigender = ubigender;
		this.ubidob = ubidob;
		this.ubiintrests = ubiintrests;
		this.ubilastaccess = ubilastaccess;
		this.createdate = createdate;
		this.modidate = modidate;
		this.ubiactive = ubiactive;
		this.ubiisverified = ubiisverified;
		this.deleted = deleted;
		this.createdby = createdby;
		this.exfiled1 = exfiled1;
		this.exfield2 = exfield2;
		this.ubiusertype = ubiusertype;
		this.ubipeavail = ubipeavail;
		this.ubihavecall = ubihavecall;
		this.ubicallmsg = ubicallmsg;
		this.ubiispaid = ubiispaid;
		this.ubiadcode = ubiadcode;
		this.ubiunquser = ubiunquser;
		this.ubiblockuser = ubiblockuser;
		this.mailblock = mailblock;
		this.exfield3 = exfield3;
		this.exfield4 = exfield4;
		this.usermodassignto = usermodassignto;
		this.isregistered = isregistered;
	}
	
	public Tpubi(String ubiemailalternate, String ubimailoption,
			String ubiemail, Long ubiprimarymobile, String ubifname,
			String ubilogin, Long ubirfnum) {

		this.ubiemailalternate = ubiemailalternate;
		this.ubimailoption = ubimailoption;
		this.ubiemail = ubiemail;		
		this.ubiprimarymobile = ubiprimarymobile;
		this.ubifname = ubifname;
		this.ubilogin = ubilogin;		
		this.ubirfnum = ubirfnum;
	}

	/** default constructor */
	public Tpubi() {
	}

	public Long getUbirfnum() {
		return ubirfnum;
	}

	public void setUbirfnum(Long ubirfnum) {
		this.ubirfnum = ubirfnum;
	}

	public Long getUbicndmaristat() {
		return ubicndmaristat;
	}

	public void setUbicndmaristat(Long ubicndmaristat) {
		this.ubicndmaristat = ubicndmaristat;
	}

	public Long getUbiassignto() {
		return ubiassignto;
	}

	public void setUbiassignto(Long ubiassignto) {
		this.ubiassignto = ubiassignto;
	}

	public Long getUbicndoccupation() {
		return ubicndoccupation;
	}

	public void setUbicndoccupation(Long ubicndoccupation) {
		this.ubicndoccupation = ubicndoccupation;
	}

	public Long getUbicndstate() {
		return ubicndstate;
	}

	public void setUbicndstate(Long ubicndstate) {
		this.ubicndstate = ubicndstate;
	}

	public Long getUbicndcountry() {
		return ubicndcountry;
	}

	public void setUbicndcountry(Long ubicndcountry) {
		this.ubicndcountry = ubicndcountry;
	}

	public Long getUbicndeducation() {
		return ubicndeducation;
	}

	public void setUbicndeducation(Long ubicndeducation) {
		this.ubicndeducation = ubicndeducation;
	}


	public Long getUbicndcity() {
		return ubicndcity;
	}

	public void setUbicndcity(Long ubicndcity) {
		this.ubicndcity = ubicndcity;
	}

	public Long getUbicndtitle() {
		return ubicndtitle;
	}

	public void setUbicndtitle(Long ubicndtitle) {
		this.ubicndtitle = ubicndtitle;
	}

	public Long getUbicndhouseincm() {
		return ubicndhouseincm;
	}

	public void setUbicndhouseincm(Long ubicndhouseincm) {
		this.ubicndhouseincm = ubicndhouseincm;
	}

	public String getUbilogin() {
		return ubilogin;
	}

	public void setUbilogin(String ubilogin) {
		this.ubilogin = ubilogin;
	}

	public String getUbipass() {
		return ubipass;
	}

	public void setUbipass(String ubipass) {
		this.ubipass = ubipass;
	}

	public String getUbihintq() {
		return ubihintq;
	}

	public void setUbihintq(String ubihintq) {
		this.ubihintq = ubihintq;
	}

	public String getUbihintans() {
		return ubihintans;
	}

	public void setUbihintans(String ubihintans) {
		this.ubihintans = ubihintans;
	}

	public String getUbifname() {
		return ubifname;
	}

	public void setUbifname(String ubifname) {
		this.ubifname = ubifname;
	}

	public String getUbimname() {
		return ubimname;
	}

	public void setUbimname(String ubimname) {
		this.ubimname = ubimname;
	}

	public String getUbilname() {
		return ubilname;
	}

	public void setUbilname(String ubilname) {
		this.ubilname = ubilname;
	}

	public String getUbiaddr1() {
		return ubiaddr1;
	}

	public void setUbiaddr1(String ubiaddr1) {
		this.ubiaddr1 = ubiaddr1;
	}

	public String getUbiaddr2() {
		return ubiaddr2;
	}

	public void setUbiaddr2(String ubiaddr2) {
		this.ubiaddr2 = ubiaddr2;
	}

	public String getUbiothercity() {
		return ubiothercity;
	}

	public void setUbiothercity(String ubiothercity) {
		this.ubiothercity = ubiothercity;
	}

	public String getUbiotherstate() {
		return ubiotherstate;
	}

	public void setUbiotherstate(String ubiotherstate) {
		this.ubiotherstate = ubiotherstate;
	}

	public Long getUbicndzip() {
		return ubicndzip;
	}

	public void setUbicndzip(Long ubicndzip) {
		this.ubicndzip = ubicndzip;
	}

	public String getUbiaddrvisible() {
		return ubiaddrvisible;
	}

	public void setUbiaddrvisible(String ubiaddrvisible) {
		this.ubiaddrvisible = ubiaddrvisible;
	}

	public String getUbiphone() {
		return ubiphone;
	}

	public void setUbiphone(String ubiphone) {
		this.ubiphone = ubiphone;
	}

	public String getUbiphone2() {
		return ubiphone2;
	}

	public void setUbiphone2(String ubiphone2) {
		this.ubiphone2 = ubiphone2;
	}

	public String getUbiphonevisible() {
		return ubiphonevisible;
	}

	public void setUbiphonevisible(String ubiphonevisible) {
		this.ubiphonevisible = ubiphonevisible;
	}

	public String getUbimobile() {
		return ubimobile;
	}

	public void setUbimobile(String ubimobile) {
		this.ubimobile = ubimobile;
	}

	public String getUbifax() {
		return ubifax;
	}

	public void setUbifax(String ubifax) {
		this.ubifax = ubifax;
	}

	public String getUbiemail() {
		return ubiemail;
	}

	public void setUbiemail(String ubiemail) {
		this.ubiemail = ubiemail;
	}

	public String getUbiemail2() {
		return ubiemail2;
	}

	public void setUbiemail2(String ubiemail2) {
		this.ubiemail2 = ubiemail2;
	}

	public String getUbiemailvisible() {
		return ubiemailvisible;
	}

	public void setUbiemailvisible(String ubiemailvisible) {
		this.ubiemailvisible = ubiemailvisible;
	}

	public String getUbicndcontmode() {
		return ubicndcontmode;
	}

	public void setUbicndcontmode(String ubicndcontmode) {
		this.ubicndcontmode = ubicndcontmode;
	}

	public String getUbiurl() {
		return ubiurl;
	}

	public void setUbiurl(String ubiurl) {
		this.ubiurl = ubiurl;
	}

	public String getUbigender() {
		return ubigender;
	}

	public void setUbigender(String ubigender) {
		this.ubigender = ubigender;
	}

	public Date getUbidob() {
		return ubidob;
	}

	public void setUbidob(Date ubidob) {
		this.ubidob = ubidob;
	}

	public String getUbiintrests() {
		return ubiintrests;
	}

	public void setUbiintrests(String ubiintrests) {
		this.ubiintrests = ubiintrests;
	}

	public Date getUbilastaccess() {
		return ubilastaccess;
	}

	public void setUbilastaccess(Date ubilastaccess) {
		this.ubilastaccess = ubilastaccess;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModidate() {
		return modidate;
	}

	public void setModidate(Date modidate) {
		this.modidate = modidate;
	}

	public String getUbiactive() {
		return ubiactive;
	}

	public void setUbiactive(String ubiactive) {
		this.ubiactive = ubiactive;
	}

	public String getUbiisverified() {
		return ubiisverified;
	}

	public void setUbiisverified(String ubiisverified) {
		this.ubiisverified = ubiisverified;
	}

	public String getDeleted() {
		return deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public Long getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	public Long getExfiled1() {
		return exfiled1;
	}

	public void setExfiled1(Long exfiled1) {
		this.exfiled1 = exfiled1;
	}

	public String getExfield2() {
		return exfield2;
	}

	public void setExfield2(String exfield2) {
		this.exfield2 = exfield2;
	}

	public String getUbiusertype() {
		return ubiusertype;
	}

	public void setUbiusertype(String ubiusertype) {
		this.ubiusertype = ubiusertype;
	}

	public String getUbipeavail() {
		return ubipeavail;
	}

	public void setUbipeavail(String ubipeavail) {
		this.ubipeavail = ubipeavail;
	}

	public String getUbihavecall() {
		return ubihavecall;
	}

	public void setUbihavecall(String ubihavecall) {
		this.ubihavecall = ubihavecall;
	}

	public String getUbicallmsg() {
		return ubicallmsg;
	}

	public void setUbicallmsg(String ubicallmsg) {
		this.ubicallmsg = ubicallmsg;
	}

	public String getUbiispaid() {
		return ubiispaid;
	}

	public void setUbiispaid(String ubiispaid) {
		this.ubiispaid = ubiispaid;
	}

	public String getUbiadcode() {
		return ubiadcode;
	}

	public void setUbiadcode(String ubiadcode) {
		this.ubiadcode = ubiadcode;
	}

	public Long getUbiunquser() {
		return ubiunquser;
	}

	public void setUbiunquser(Long ubiunquser) {
		this.ubiunquser = ubiunquser;
	}

	public String getUbiblockuser() {
		return ubiblockuser;
	}

	public void setUbiblockuser(String ubiblockuser) {
		this.ubiblockuser = ubiblockuser;
	}

	public String getMailblock() {
		return mailblock;
	}

	public void setMailblock(String mailblock) {
		this.mailblock = mailblock;
	}

	public String getExfield3() {
		return exfield3;
	}

	public void setExfield3(String exfield3) {
		this.exfield3 = exfield3;
	}

	public String getExfield4() {
		return exfield4;
	}

	public void setExfield4(String exfield4) {
		this.exfield4 = exfield4;
	}

	public Long getUsermodassignto() {
		return usermodassignto;
	}

	public void setUsermodassignto(Long usermodassignto) {
		this.usermodassignto = usermodassignto;
	}

	public String getIsregistered() {
		return isregistered;
	}

	public void setIsregistered(String isregistered) {
		this.isregistered = isregistered;
	}

	public Long getUbisuperuser() {
		return ubisuperuser;
	}

	public void setUbisuperuser(Long ubisuperuser) {
		this.ubisuperuser = ubisuperuser;
	}

	public String getUbiemailverified() {
		return ubiemailverified;
	}

	public void setUbiemailverified(String ubiemailverified) {
		this.ubiemailverified = ubiemailverified;
	}

	public Long getUbiprimarymobile() {
		return ubiprimarymobile;
	}

	public void setUbiprimarymobile(Long ubiprimarymobile) {
		this.ubiprimarymobile = ubiprimarymobile;
	}

	public String getUbiemailalternate() {
		return ubiemailalternate;
	}

	public void setUbiemailalternate(String ubiemailalternate) {
		this.ubiemailalternate = ubiemailalternate;
	}

	public String getUbiautoregister() {
		return ubiautoregister;
	}

	public void setUbiautoregister(String ubiautoregister) {
		this.ubiautoregister = ubiautoregister;
	}

	public Integer getUbifreelisting() {
		return ubifreelisting;
	}

	public void setUbifreelisting(Integer ubifreelisting) {
		this.ubifreelisting = ubifreelisting;
	}

	public String getUbidispupfront() {
		return ubidispupfront;
	}

	public void setUbidispupfront(String ubidispupfront) {
		this.ubidispupfront = ubidispupfront;
	}

	public Long getUbiprimarymobileisd() {
		return ubiprimarymobileisd;
	}

	public void setUbiprimarymobileisd(Long ubiprimarymobileisd) {
		this.ubiprimarymobileisd = ubiprimarymobileisd;
	}

	public String getUbitoken() {
		return ubitoken;
	}

	public void setUbitoken(String ubitoken) {
		this.ubitoken = ubitoken;
	}

	public Long getUbiphonestd() {
		return ubiphonestd;
	}

	public void setUbiphonestd(Long ubiphonestd) {
		this.ubiphonestd = ubiphonestd;
	}

	public Long getUbicndphoneisd() {
		return ubicndphoneisd;
	}

	public void setUbicndphoneisd(Long ubicndphoneisd) {
		this.ubicndphoneisd = ubicndphoneisd;
	}

	public int getUbiSpamscore() {
		return ubiSpamscore;
	}

	public void setUbiSpamscore(int ubiSpamscore) {
		this.ubiSpamscore = ubiSpamscore;
	}

	


	/** minimal constructor 
	public Tpubi(Long ubirfnum, Tpcnd tpcndByUbicndstate,
			Tpcnd tpcndByUbicndcountry, Tpcnd tpcndByUbicndcity,
			Tpcnd tpcndByUbicndtitle, String ubilogin, String ubifname,
			String ubilname, String ubiaddr1, String ubiaddrvisible,
			String ubiphonevisible, String ubiemailvisible, Date createdate,
			Date modidate, String ubiactive, String ubiisverified,
			String deleted, Long createdby, String ubiusertype) {
		this.ubirfnum = ubirfnum;
		this.tpcndByUbicndstate = tpcndByUbicndstate;
		this.tpcndByUbicndcountry = tpcndByUbicndcountry;
		this.tpcndByUbicndcity = tpcndByUbicndcity;
		this.tpcndByUbicndtitle = tpcndByUbicndtitle;
		this.ubilogin = ubilogin;
		this.ubifname = ubifname;
		this.ubilname = ubilname;
		this.ubiaddr1 = ubiaddr1;
		this.ubiaddrvisible = ubiaddrvisible;
		this.ubiphonevisible = ubiphonevisible;
		this.ubiemailvisible = ubiemailvisible;
		this.createdate = createdate;
		this.modidate = modidate;
		this.ubiactive = ubiactive;
		this.ubiisverified = ubiisverified;
		this.deleted = deleted;
		this.createdby = createdby;
		this.ubiusertype = ubiusertype;
	}
*/


}